### ISSUE TITLE
Rogue var_dump()

### ISSUE THREAD

**Issue by bellwood** [iranimij/automatic-upload-images#6]
There is a rogue var_dump() on line 28 of admin/ImageUploader.php, [here](https://github.com/iranimij/automatic-upload-images/blob/3b10ac57927a86ee4b0c6245accb4ef31dfc4755/admin/ImageUploader.php#L28)

Having fixed that locally, running Wordpress 5.6.2 and bulk editing posts that were imported from Ghost yields no images uploaded the media gallery or replacements made within posts.

**Comment by iranimij** [comment]
Hi man, 
that var_dump was deleted. But
Would you please send me the URL that you want to upload images from it? I need to replicate the problem.

**Comment by iranimij** [comment]
did you install Classic Editor plugin in your site ?

**Comment by iranimij** [comment]
@avnkhanh We have had an update please update your plugin and check again.

**Comment by bellwood** [comment]
I've installed it now and made it the default editor. With that alone, still no image import.

In reviewing the code further, I've found some additional issues:

1) None of my images from ghost have the domain in the src/srcset, they are all anchored to `/content/`, so when [$this->validate()](https://github.com/iranimij/automatic-upload-images/blob/1fc42b546735ed6c9c059973208129bb1947c387/admin/ImageUploader.php#L163) runs inside the the `save` method, `$url` will be empty.

I fixed this inside the `save` method by checking `$this->url` to see if the domain path exists in the URL and if not, prepend it.

```
        if(substr($this->url, 0, 28) != 'http://myredacteddomain.com') {
            $this->url = 'http://myredacteddomain.com'.$this->url;
        }
```

Note that the FQDN and len should probably be pulled `site_url('url')`.

2) [validate](https://github.com/iranimij/automatic-upload-images/blob/1fc42b546735ed6c9c059973208129bb1947c387/admin/ImageUploader.php#L55) has a bad comparison, you want is not equal to and need to wrap in parens correctly: `if (($url != $site_url) || !$url) {` else, if they DO match, it won't work.

With these two fixes, I do see images being downloaded, HOWEVER it is not using the dates in the path of the src images for the media library, e.g images from say `/wp-content/uploads/2020/10/example.jpg` are being saved in `/wp-content/uploads/2021/03/example.jpg`

I DO see replacement within the posts though so that appears to be working OK though.

**Comment by iranimij** [comment]
@bellwood  We have had an update, Could you please update your plugin and check it again?

**Comment by bellwood** [comment]
@iranimij will do and report back

**Comment by bellwood** [comment]
@iranimij updated the plugin, purged all my posts, re-imported ghost export, edited 20 posts and saved - nothing.

**Comment by iranimij** [comment]
Can you send me your site information?  iranimij[@]gmail.com

**Comment by bellwood** [comment]
@iranimij done - thanks =)
